### ISSUE TITLE
Pretty sure one of the function checks is incorrect

### ISSUE THREAD

**Issue by keilkyle** [learn-co-curriculum/phase-1-javascript-functional-library-project#3]
### Canvas Link

https://learning.flatironschool.com/courses/4978/assignments/167577?module_item_id=362251

### Concern

I'm pretty sure this test in indexTest.js is wrong. 

If you run myReduce on [1, 2, 3, 4] and your function just multiplies things by 3 and adds them together, you should get 3+6+9+12 = 30, not 28.

`  describe('myReduce', function () {
    const testArr = unmodifiedTestArr.slice() // arr is [1, 2, 3, 4]
    const testObj = Object.assign({}, unmodifiedTestObj) // obj is {one: 1, two: 2, three: 3, four: 4}
    const callback = (acc, val, collection) => (acc + (val * 3))

    it('returns the correct reduced value when passed an initial value', function () {
      const reduceWithAcc = myReduce(testArr, callback, 10)
      expect(reduceWithAcc).to.equal(40)
    })

    it('returns the correct reduced value when not passed an initial value', function () {
      const reduceSansAcc = myReduce(testArr, callback)
      expect(reduceSansAcc).to.equal(28)
    })`

### Suggested Changes

Just modify the correct answer to 30

**Comment by graciemcguire** [comment]
Hey @keilkyle, thanks for raising this issue. 
In the instructions it states on line 45 that:

>  "If a start value is not passed to `myReduce`, the first value in the collection should be used as the start value."

I'm going to close this issue, but if you need anymore explanation please either:

- Reach out to your instructor (if you've started the program and have an
  instructor)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

Thanks!
